### ISSUE TITLE
[Bug] [v5.0.4] Moyenne faussé par les matières divisées en sous parties

### ISSUE THREAD

**Issue by MattiaPARRINELLO** [Bastian-Noel/CustomDirecte#7]
Bonjour, la moyenne générale ne peut être calculer par l'extension. Il m'affiche chargement indéfiniment... J'ai donc jeté un coup d'oeuil dans la console et je retrouve cette erreur : 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at averageLoad (start.js:227:55)
    at MutationObserver.<anonymous> (start.js:135:13)
```

**Comment by Bastian-Noel** [comment]
T'a version est t'elle la derniere sortie ?
[ la 5.0.3 ]

**Comment by Bastian-Noel** [comment]
Peut-tu aussi m'envoyer les log avec l'option de debug activé :
- Clic repetitif sur le numéraux de version
- Accepter le mod debug
- Puis la console affiche de nouvelle choses
![image](https://user-images.githubusercontent.com/71983581/217331050-9cde3d0a-e99c-46e9-9a04-3572d98b75aa.png)

**Comment by MattiaPARRINELLO** [comment]
Je suis bien sur la version 5.0.3, voici le nouveau console log

```
averageCalculator | Page de note chargé --> Calcule de moyenne
start.js:56 Debug | averageCalculator | Zone de la date du derniere calcule --> Mise à jour
start.js:56 Debug | averageCalculator | Div de moyenne Générale --> Crée
start.js:56 Debug | averageCalculator | Colone : coef --> Trouver
start.js:56 Debug | averageCalculator | Colone : relevemoyenne --> Trouver
start.js:56 Debug | averageCalculator | Colone : notes --> Trouver
start.js:56 Debug | averageCalculator | > Analyse du Tableau de note
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16.5  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 13  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 14.428571428571429  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 13  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 17.75  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 11  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 14.875  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 16  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 20  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 13  -  coeficient : 1.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 12  -  coeficient : 1.5
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 13.571428571428571  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14.5  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16.5  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 16.1  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 13  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 13  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 11.5  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 12.75  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 14  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 9  -  coeficient : 3
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 18  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 20  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14  -  coeficient : 3
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 20  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 14.7  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 12  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 8.8  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 7.5  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 14  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 17.5  -  coeficient : 0.75
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 12.273333333333333  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 13  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 17  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 10  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 12  -  coeficient : 2
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 10  -  coeficient : 0.5
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 12.454545454545455  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 16  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 17  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 16.5  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> Analyse d'une nouvelle ligne du tableau
start.js:56 Debug | averageCalculator | > --> > Nouvelle note : 18  -  coeficient : 1
start.js:56 Debug | averageCalculator | > --> >> Moyenne de la ligne 18  -  coeficient : 1
start.js:227 Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at averageLoad (start.js:227:55)
    at MutationObserver.<anonymous> (start.js:135:13)
```

Voici le screen de mes notes
![image](https://user-images.githubusercontent.com/66528113/217938556-0c1a46ce-a18c-4256-8d11-4021836c1db6.png)

**Comment by Bastian-Noel** [comment]
J'aimerais bien savoir si la moyenne afficher est celle de l'établissement ou si une autre extension est installer ?

Sinon je vois deux problèmes majeurs : 
- Les matières ayant une partie oral et écrit n'ont pas été prévus, ce qui risque de fausser les moyennes.
- Un bug d'origine inconnue (peut être lié au problème précédent) empêche le calcul de la moyenne générale.

**Comment by Bastian-Noel** [comment]
Je vais me essayer de voir ce que je peut faire mais c'est compliqué de modifier le code sans savoir comment fonctionne ton EcoleDirecte (chaque établissement à c'est spécificité).

Si possible j'aimerais bien te contacter sur discord pour pouvoir te poser des questions,ou de demander des manipulations si cela te gêne pas.

Mon discord : Bastoon😅#1563

**Comment by MattiaPARRINELLO** [comment]
C'est celle qui est affichée par l'établissement, je t'ajoute sur discord

**Comment by MattiaPARRINELLO** [comment]
**__UPDATE pour les gens qui ont le même problème :__** Le problème est en cours de correction, celui-ci devrait être bientôt réglé, je vous tiens informé une fois résolu

**Comment by Bastian-Noel** [comment]
Mettre a jours vers la v5.0.5
